pipeline {
    agent any

    environment {
        DB_URL = "${env.DB_URL}"
        DB_USERNAME = "${env.DB_USERNAME}"
        DB_PASSWORD = "${env.DB_PASSWORD}"
        DOCKER_CREDENTIALS_ID = "dockerHub"

    }

    stages {
        stage('Docker Login') {
                steps {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                         sh '''
                             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                         '''
                    }
                }
            }

        stage('Debug') {
            steps {
                sh '''
                    echo "DB_URL: $DB_URL"
                    echo "DB_USERNAME: $DB_USERNAME"
                '''
            }
        }

        stage('Build') {
            steps {
                dir('smartcap-back') {
                    sh '''
                        chmod +x gradlew
                        ./gradlew build -x test
                    '''
                }
            }
        }

        stage('Docker Build & Deploy') {
            steps {
                dir('smartcap-back') {
                    sh '''
                        docker stop smartcap-back || true
                        docker rm smartcap-back || true
                        docker rmi smartcap-back || true
                        docker build -t smartcap-back .

                        docker network inspect smartcap-network >/dev/null 2>&1 || \
                        docker network create smartcap-network

                        docker run -d \
                            --name smartcap-back \
                            --network smartcap-network \
                            -p 8080:8080 \
                            -v smartcap-back-volume:/app/data \
                            -e DB_URL=$DB_URL \
                            -e DB_USERNAME=$DB_USERNAME \
                            -e DB_PASSWORD=$DB_PASSWORD \
                            smartcap-back
                    '''
                }
            }
        }
    }
}