pipeline {
    agent any

    environment {
        SPRING_DATASOURCE_URL = "${env.SPRING_DATASOURCE_URL}"
        SPRING_DATASOURCE_USERNAME = "${env.SPRING_DATASOURCE_USERNAME}"
        SPRING_DATASOURCE_PASSWORD = "${env.SPRING_DATASOURCE_PASSWORD}"
        SPRING_DATASOURCE_DRIVER_CLASS_NAME = "${env.SPRING_DATASOURCE_DRIVER_CLASS_NAME}"
    }

    stages {
        stage('Debug') {
            steps {
                sh '''
                    echo "SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL"
                    echo "SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME"
                '''
            }
        }

        stage('Build') {
            steps {
                dir('smartcap-back') {
                    sh '''
                        chmod +x gradlew
                        ./gradlew build -x test
                    '''
                }
            }
        }

        stage('Docker Build & Deploy') {
            steps {
                dir('smartcap-back') {
                    sh '''
                        docker stop smartcap-back || true
                        docker rm smartcap-back || true
                        docker rmi smartcap-back || true
                        docker build -t smartcap-back .

                        docker network inspect smartcap-network >/dev/null 2>&1 || \
                        docker network create smartcap-network

                        docker run -d \
                            --name smartcap-back \
                            --network smartcap-network \
                            -p 8080:8080 \
                            -v smartcap-back-volume:/app/data \
                            -e SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
                            -e SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
                            -e SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
                            -e SPRING_DATASOURCE_DRIVER_CLASS_NAME=$SPRING_DATASOURCE_DRIVER_CLASS_NAME \
                            smartcap-back
                    '''
                }
            }
        }
    }
}
