pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = "dockerHub"
    }


    stages {
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS_ID}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh '''
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                dir('smartcap-front') {
                    sh '''
                        docker stop smartcap-front || true
                        docker rm smartcap-front || true
                        docker rmi smartcap-front || true
                        docker build -t smartcap-front .
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    docker network inspect smartcap-network >/dev/null 2>&1 || \
                    docker network create smartcap-network

                    docker run -d \
                        --name smartcap-front \
                        --network smartcap-network \
                        -p 5173:80 \
                        smartcap-front
                '''
            }
        }
    }
}